### ISSUE TITLE
Нет показаний

### ISSUE THREAD

**Issue by nemoyar** [raxers/elehant_water#3]
Переехал с rpi zero w на rpi4b+, перестали приходить показания счетчиков, ошибок в HA нет.
в lovalace так
![image](https://user-images.githubusercontent.com/16333431/100877525-f5a8b300-34b9-11eb-8e4c-3c9903e2780d.png)
В консоли даю python3 -m aioblescan - опрос устройств бегает, но через пару секунд тормозит с такой ошибкой:
![image](https://user-images.githubusercontent.com/16333431/100877448-d7db4e00-34b9-11eb-8023-63ebbbe08edd.png)

**Comment by nemoyar** [comment]
Спустя сутки данные появились

**Comment by kirkorblack** [comment]
Я тоже с этим бился(
Косяк во встроенном синезубе на 4 малине...
Как только его отключил и воткнул обычный USB-Bluetooth все взлетело идеально

**Comment by raxers** [comment]
Аналогичная проблема и 3м raspbery pi.
Отваливался регулярно у меня. Но я потом переехал на обычный сервер +BT модуль, последние пару месяцев все стабильно работает
