### ISSUE TITLE
Expected data source not listed

### ISSUE THREAD

**Issue by Hawk-3** [raxers/elehant_water#9]
В новой версии HA 2022.11 появилась возможность отслеживать потребление воды, но сенсор не виден в интрефейсе выбора
![Снимок экрана от 2022-11-03 21-36-38](https://user-images.githubusercontent.com/64266629/199806723-d514fa6c-31e5-4aa3-a4f1-e5874b8cf791.png)
https://www.home-assistant.io/more-info/statistics/

**Comment by Hawk-3** [comment]
У себя добавил:
```    @property
    def device_class(self):
        """Return device class."""
        return "water"
```
У сенсора появился класс девайса:
![Снимок экрана от 2022-11-03 22-30-24](https://user-images.githubusercontent.com/64266629/199817473-0c8c515c-527d-4945-a2bf-e8313a7b00e2.png)

Но вот со state_class такое не прокатило (
```    @property
    def state_class(self):
        """Return state class."""
        return "total_increasing"
```

**Comment by Hawk-3** [comment]
В общем пришлось "закостылить" и просто сделать еще два сенсора на основании счетчиков.

У них присутствует state_class: total_increasing и необходимые unit_of_measurement

![Снимок экрана от 2022-11-07 01-27-35](https://user-images.githubusercontent.com/64266629/200198603-30f6a923-fc25-4d2b-883d-aeb79fe4c9f0.png)
![Снимок экрана от 2022-11-07 01-26-49](https://user-images.githubusercontent.com/64266629/200198605-5c6b0043-f079-46e1-bba0-c7388cc40381.png)
![Снимок экрана от 2022-11-07 01-31-57](https://user-images.githubusercontent.com/64266629/200198802-e38f0895-1329-4111-8a1c-bfa963af997b.png)


```template:
  - sensor:
      - name: "Natural gas consumption"
        unit_of_measurement: "m³"
        device_class: gas
        state_class: total_increasing
        state: "{{ states('sensor.natural_gas')|float(0) }}"
        availability: "{{ states('sensor.natural_gas')|is_number }}"

      - name: "Water cold consumption"
        unit_of_measurement: "m³"
        device_class: water
        state_class: total_increasing
        state: "{{ (states('sensor.kholodnaia_voda')|float(0) / 1000) | round (3, default=0) }}"
        availability: "{{ states('sensor.kholodnaia_voda')|is_number }}"```

**Comment by SzenProgs** [comment]
Внес правки в код. Обновляйтесь с форка.

**Comment by Hawk-3** [comment]
Спасибо большое!!!

**Comment by Hawk-3** [comment]
> Внес правки в код. Обновляйтесь с форка.

Обновился! Все отлично.
![Снимок экрана от 2022-11-07 14-09-37](https://user-images.githubusercontent.com/64266629/200296177-8243c246-328e-4ed6-9d51-6d141e9c4465.png)
![Снимок экрана от 2022-11-07 14-09-07](https://user-images.githubusercontent.com/64266629/200296181-6a8845d5-2af7-4a1c-bd09-36e51005d55f.png)
